### ISSUE TITLE
Right clicking vanilla blocks (bed, doors, etc.) causes "Unknown Error" and client crash.

### ISSUE THREAD

**Issue by warezit** [progwml6/HungerOverhaul#77] opened 2015-02-07 21:52 UTC
I have a custom modpack, and some people are running into this issue: https://github.com/warezit/zitCraft/issues/5

Forge 10.13.2.1236
HugerOverhaul 1.7.10 beta 5

Seems to be an issue with Hunger Overhaul. 
Logs here:
https://gist.github.com/Rader2146/4649332311912be56fb4
https://gist.github.com/Rader2146/e8310c933c5b9ddc2dbe

Any help/advice is appreciated.

**Comment by squeek502** [comment] 2015-02-17 00:56
@warezit, this may have been fixed by eae6ce678a00c047b381fbdeb40efb6973647fed

Did you by chance have any .json files (or any files at all) in the `config/HungerOverhaul/` directory?

**Comment by warezit** [comment] 2015-02-17 03:37
@squeek502 Nope, no files at all in the `/config/HungerOverhaul/` directory.

I did look thru all the other issues regarding "right clicking" issues etc. here: https://github.com/progwml6/HungerOverhaul/issues?q=right+click but still came up empty handed.

I hate to say it, but we ended up removing HO and SoL from our modpack, due to this issue, and some others issues as well. (non-HO related)

I think the combination of the 2 mods (HO & SoL) is great, and I would like to include them at some point in the future, but I am just trying to avoid any hiccups right now.

If you would like any other info to help diagnose this, I would be happy to share anything else I know.

**Comment by squeek502** [comment] 2015-02-17 03:48
I'm not sure what would be causing it, but the crash should not longer occur due to eae6ce6. If you have a reliable way to reproduce the crash, try [this build](https://dvs1.progwml6.com/jenkins/user/squeek502/my-views/view/All/job/HungerOverhaul-1.7.10/51/artifact/build/libs/HungerOverhaul-1.7.10-beta.6.jenkins51.jar) and see if it still happens.

Sorry for being so late to respond.

**Comment by usafphoenix** [comment] 2015-04-28 06:12
i'm not crashing, so i posted a new issue on the right-click dynamic. but i imagine when one of the issues is solved, it may solve the other issue..... for me, after right-clicking crops to harvest them....i won't be able to open my golden bag again, or ender pouch or anything similar (inventory container).

**Comment by squeek502** [comment] 2015-08-12 05:12
Going to assume this was fixed.

**Closed by squeek502** 2015-08-12 05:12 UTC
