### ISSUE TITLE
HungerOverhaul + cutlass + wither crash

### ISSUE THREAD

**Issue by Aeroxia** [progwml6/HungerOverhaul#114] opened 2015-12-21 08:26 UTC
With tinkers construct and hunger overhaul, if you have the well fed buff from eating and block while taking wither damage with a cutlass (specifically a cutlass), the game will crash in single player or "Internal server error" boot you in multiplayer.

That was a mouthful. Hunting down the source was not easy.

Crash log: http://pastebin.com/SGaTB5xa

Minecraft 1.7.10
Forge 10.13.4.1558
TConstruct-1.7.10-1.8.5
HungerOverhaul-1.7.10-1.0.0

(Posted to Tinkers Construct too: https://github.com/SlimeKnights/TinkersConstruct/issues/1839)

**Comment by squeek502** [comment] 2015-12-21 19:11
Without HO this crash doesn't happen?

**Comment by Aeroxia** [comment] 2015-12-21 19:20
Right. It only happens with "Well fed" on as well.

**Comment by squeek502** [comment] 2015-12-21 19:27
Very strange, thanks for the detailed reproduction steps.

From the crash log, it kind of seems like this could be a vanilla bug that these mods happen to be triggering, but I'll have to look into it more to confirm/deny that. The potion system is something I'm very unfamiliar with, unfortunately.

**Comment by Aeroxia** [comment] 2015-12-21 19:42
I originally posted about a week ago on a subreddit asking where I should report this, thinking it may be something deeper too. Could it be something in forge?

**Comment by Aeroxia** [comment] 2015-12-21 20:06
Hold on, sorry. I just tried with some other effects, and it did it too. It happens without HO afterall (at least with regeneration and fire resistance, but not night vision).

It seems to be Tinkers Construct or something lower down.

**Comment by squeek502** [comment] 2015-12-21 20:15
Yeah, I'm not sure what would be causing it. The [error itself](https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html) is probably caused by something being removed from the `activePotionsMap` while it's being iterated in `EntityLivingBase.updatePotionEffects` (the MCP name of `EntityLivingBase.func_70679_bo`). If that's true, then it would likely be happening either in another thread (hard to debug, not likely unless you have some mod that attempts to multi-thread the game) or inside some `PotionEffect`'s `onUpdate` method.

I'll check the vanilla PotionEffect implementations to see if there's anything that I can see.

Seems like it's gonna be a tough one to debug. Good luck. Closing this as it's unrelated to HO.

**Closed by squeek502** 2015-12-21 20:15 UTC

**Comment by squeek502** [comment] 2015-12-21 20:24
At a quick glance, I can't see anything that would cause it. But my best guess is that either some potion effect is being added in a `PotionEffect.onUpdate` method or some potion effect is being removed in a `PotionEffect.onUpdate` method. `PotionEffect.onUpdate` kind of leads down a rabbit hole of other methods being called, though, so it's not easy to see exactly where it might be happening.

**Comment by Aeroxia** [comment] 2015-12-21 20:29
It seems it's come up with Galacticraft too, and they linked to here: https://github.com/MinecraftForge/MinecraftForge/issues/1695

I'm not sure how much I understand of this right now.

**Comment by squeek502** [comment] 2015-12-21 20:33
I saw that issue as well, but it actually seems unrelated. That error is caused by invalid potion effect IDs being registered, whereas yours is caused by something doing some improper manipulation of the activePotionEffect map during runtime.

My advice would be to try to narrow it down as much as you possibly can. Install *only* Tinkers Construct + Mantle + Forge and see if you can still recreate it. If not, then you've got a very, very messy problem on your hands and it's going to be very tough to figure it out.

**Comment by Aeroxia** [comment] 2015-12-21 20:38
I confused myself a little bit ago and editted in another crash log, with just those 3 you said.  (Then went and put it on the Tinkers page where I originally intened <_<)  So yeah, reproducible with just those.
