### ISSUE TITLE
Pam's Harvestcraft fruit trees drop fruit blocks.

### ISSUE THREAD

**Issue by SmityJagerMan** [progwml6/HungerOverhaul#167] opened 2018-01-11 22:11 UTC
## Version Information
`Minecraft: `1.12.2
`Forge: `14.23.1.2555
`Mantle: `1.3.1.21
`Natura: `4.3.1.35

## Report Information

![34736057-f48cb9d8-f571-11e7-9b49-59d6817e5b00](https://user-images.githubusercontent.com/35350618/34850033-a03e4d26-f6e1-11e7-89fb-89be44e6272e.png)

## Steps to Reproduce

Right click to collect fruit from HarvestCraft fruit trees

**Comment by SmityJagerMan** [comment] 2018-01-11 22:13
When collecting fruit, hunger overhaul will cause the fruit and fruit blocks to be dropped.

**Comment by Insane96** [comment] 2018-01-14 10:11
Already reported and Fixed: https://github.com/progwml6/HungerOverhaul/issues/163

**Comment by alexbegt** [comment] 2018-01-18 18:42
Duplicate of #163 and it has been fixed but not pushed yet.

**Closed as completed by alexbegt** 2018-01-18 18:42 UTC
