### ISSUE TITLE
Seed Module Broken

### ISSUE THREAD

**Issue by ElvenChaos** [progwml6/HungerOverhaul#175] opened 2018-01-26 08:15 UTC
## Version Information
`Minecraft: `1.12.2
`Forge: `2604
`Mantle: `none
`Natura: `none
`Apple Core: `3.1.0
`Hunger Overhaul: `1.3.0 jenkins 139

## Report Information

The seed harvesting module seems to be broken, as using the hoe on vanilla grass does de-grass the block, but any time a seed would have spawned errors get thrown at the console (I'm using multimc for testing).

Also, the module is not stopping seeds from dropping from grass.
## Steps to Reproduce

```
"getting seeds" {
    # Adds a crafting recipe to turn 1 wheat into 1 seed [vanilla: false] [default: true]
    B:addSeedsCraftingRecipe=true

    # Each seed has an equal chance to drop (grass drops and via hoes) [vanilla: false] [default: true]
    B:allSeedsEqual=true

    # Multiplier on tool damage taken when a hoe is used ('modifyHoeUse' must be true) [vanilla: 1] [range: 1 ~ 2147483647, default: 5]
    I:hoeToolDamageMultiplier=4

    # Changes the use of hoes depending on the availability of water [vanilla: false] [default: true]
    B:modifyHoeUse=true

    # Whether wood and stone hoe recipes are removed [vanilla: false] [default: true]
    B:removeHoeRecipes=false

    # Removes seed drops when breaking tall grass [vanilla: false] [default: true]
    B:removeTallGrassSeeds=true

    # Percent chance for seed to drop from hoe use on normal difficulty ('modifyHoeUse' must be true) [vanilla: 20] [range: 0 ~ 100, default: 20]
    I:seedChance=25
}
```
Cheat in a hoe and till some grass away from water.

## Forge Log

The errors did _not_ record in the client-latest or the latest logs, but _did_ record in my multimc console.
[Console with errors](https://gist.github.com/ElvenChaos/b9ea60b6d6b916b1661976a835b69063) _Errors are here!_
[fml-client-latest.log](https://gist.github.com/ElvenChaos/7bbd6c1c3f617812994ff528274f6415) _Errors not present._
[Plain latest.log](https://gist.github.com/ElvenChaos/0dbb6a4cae1c7148919bd648bd1f430b) _Errors not present._

**Comment by ElvenChaos** [comment] 2018-01-31 03:46
Bug still valid in HO 131 jenkins 142.

**Comment by ElvenChaos** [comment] 2018-02-05 20:34
@alexbegt Is there any confirmation on this bug? It seems pretty major that an entire module/feature is completely broken on its own, without other mod interaction. I understand if the fix just takes time to do. Were you able to confirm and reproduce it?

**Comment by CcytherR** [comment] 2018-02-14 18:02
yes confirmed this setting is not working.
    # Removes seed drops when breaking tall grass [vanilla: false] [default: true]
    B:removeTallGrassSeeds=true 
Seeds still drop when breaking grass by hand also seems its been this way ever since 1.8+
Its one the unique things this mod does and one of the main reasons id use it

**Comment by Unknown-Zombie** [comment] 2018-06-04 02:32
Came here to report the same thing. This is still an issue in 1.3.3 jenkins 148

**Comment by The-Arcanian** [comment] 2018-06-24 00:55
`addSeedsCraftingRecipe` and `hoeToolDamageMultiplier` work for me. `modifyHoeUse` will de-grass blocks but will not drop seeds. None of the others seem to work.

HungerOverhaul-1.12.2-1.3.3.jenkins148
forge-1.12.2-14.23.4.2705

**Comment by ghost** [comment] 2018-07-03 19:00
B:removeTallGrassSeeds=true will not work, HO don't load the GrasSeedsModule in HungerOverhaul.java

With an activated GrasSeedsModule only 1 seed drop out of >300 try's

Using a hoe give 1 seed out of ~3 try's

I'm not sure why it's commented out, but there must be a reason in one version since MC1.7.10

```
    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
        //if (Config.removeTallGrassSeeds || Config.allSeedsEqual)
        //{
        //    GrassSeedsModule.postInit();
        //}

        VanillaModule.postInit();
        TweaksModule.postInit();
        VillageModule.postInit();
        LootModule.postInit();

        MinecraftForge.EVENT_BUS.register(new HungerOverhaulEventHook());
        MinecraftForge.EVENT_BUS.register(new RespawnHungerModule());
        MinecraftForge.EVENT_BUS.register(new LootModule());
}
```

**Comment by paulgb434** [comment] 2019-05-02 18:32
Yeah it's unfortunate this still isn't fixed in 2019. BetterWithMod's "HCSeeds" option serves as a good enough replacement for this module fortunately.

**Closed as completed** 2019-05-03 14:56 UTC

**Comment by Astavie** [comment] 2019-10-20 16:07
I see this issue has been fixed (like 6 months ago), but curseforge still contains an outdated version. I'd really like to be able to have a functional seed module in my modpack
