### ISSUE TITLE
Crash with Biomes O' Plenty

### ISSUE THREAD

**Issue by Kippy232** [progwml6/HungerOverhaul#186] opened 2018-04-16 16:19 UTC
## Version Information
`Minecraft: ` 1.12.2
`Forge: ` 1.12.2-14.23.3.2655
`Mantle: ` N/A
`Natura: ` N/A
`Apple Core: ` 1.12.2-3.1.1
`Hunger Overhaul: ` 1.12.2-1.3.1.jenkins144

## Report Information

Hunger Overhaul 1.3.1 crashes and fails to fully load with Biomes O' Plenty versions AFTER 7.0.1.2354. Excerpt from BOP changelog, version 7.0.1.2355: Removed Turnips, Ambrosia, Salads, Jelled Poison, and Pinecones.

## Steps to Reproduce

Begin Minecraft 1.12.2 with the latest version of Hunger Overhaul and any version of Biomes O' Plenty after and including 7.0.1.2355.

## Crash Log

https://pastebin.com/ChjiAdrB

## Forge Log

https://pastebin.com/U2yerHWc

**Comment by alexbegt** [comment] 2018-04-16 18:00
This is a duplicate of #185 , but I have already fixed the bug, but have not had the time to push a new build to curse. It should be out later tonight.

**Closed as completed by alexbegt** 2018-04-16 18:00 UTC
Labels: bug, duplicate
